name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged

      postgres:
        image: postgres:12.2-alpine
        environment:
          POSTGRES_DB: nakama
          POSTGRES_PASSWORD: localdb
        ports:
          - 5432:5432
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d nakama"]
          interval: 3s
          timeout: 3s
          retries: 5

      nakama:
        image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
        entrypoint:
          - "/bin/sh"
          - "-ecx"
          - >
              /nakama/nakama migrate up --database.address postgres://localdb:localdb@postgres:5432/nakama &&
              exec /nakama/nakama --name nakama1 --database.address postgres://localdb:localdb@postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200
        depends_on:
          postgres:
            condition: service_healthy
        ports:
          - 7349:7349
          - 7350:7350
          - 7351:7351
        healthcheck:
          test: ["CMD", "/nakama/nakama", "healthcheck"]
          interval: 10s
          timeout: 5s
          retries: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose services
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Run tests or additional commands
        run: |
          # Add any additional commands here, such as running tests against your services

      - name: Stop Docker Compose services
        run: docker-compose down
